title: Product
'@id': schema:Product
extends: Thing
role: tertiary
status: stable
category: metadata
description: |
  Any offered product or service. For example, a pair of shoes;
  a haircut; or an episode of a TV show streamed online.
properties:
  brands:
    '@id': schema:brand
    description: Brands that the product is labelled with.
    type: array
    items:
      $ref: Brand
  logo:
    '@id': schema:logo
    description: The logo of the product.
    anyOf:
      - type: string
        format: uri
      - $ref: ImageObject
  productID:
    '@id': schema:productID
    description: Product identification code.
    type: string
