title: SoftwareEnvironment
'@id': stencila:SoftwareEnvironment
extends: Thing
role: primary
status: experimental
category: code
description: A computational environment.
properties:
  extends:
    '@id': stencila:extends
    description: Other environments that this environment extends by adding or removing packages.,
    type: array
    items:
      $ref: SoftwareEnvironment
  adds:
    '@id': stencila:adds
    description: The packages that this environment adds to the base environments listed under `extends` (if any).,
    type: array
    items:
      $ref: SoftwareSourceCode
  removes:
    '@id': stencila:removes
    description: The packages that this environment removes from the base environments listed under `extends` (if any).,
    type: array
    items:
      $ref: SoftwareSourceCode
required:
  - name
